#!/bin/sh
#------------------------------------------------------------------------------
# License
#     Copyright (C) 2011-2013 blueCAPE Lda
#
#     This file is part of blueCAPE's unofficial mingw patches for OpenFOAM.
#     For more information about these patches, visit:
#         http://www.bluecape.com.pt/blueCFD
#
#     This file is a derivative work of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     AllwcleanRegEx
#
# Description
#     Clean the build folders for RegEx for mingw.
#
#------------------------------------------------------------------------------
# run from third-party directory only
cd ${0%/*} || exit 1
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

if ! isMinGW; then
  echo "Error: this script is meant to be used for MinGW compilers only!"
  exit 1
fi

#set script options
REGEXNAMENVERSION=mingw-libgnurx-2.5.1
REGEXBUILD="$WM_THIRD_PARTY_DIR/build/$WM_ARCH$WM_COMPILER/$REGEXNAMENVERSION"
REGEXTARGET="$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER/$REGEXNAMENVERSION"

rm -rf $REGEXBUILD
rm -rf $REGEXTARGET
