#! /bin/bash
#------------------------------------------------------------------------------
# License
#     Copyright (C) 2011-2014 blueCAPE Lda
#
#     This file is part of blueCAPE's unofficial mingw patches for OpenFOAM.
#     For more information about these patches, visit:
#         http://bluecfd.com/Core
#
#     This file is a derivative work of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     genOPENMPIstubs
#
# Description
#     This script generates the link library and prepares the include 
#   files for the pre-built version of Open-MPI for Windows.
#
#------------------------------------------------------------------------------

if ! isMinGW; then
  echo "Error: this script is meant to be used for MinGW compilers only!"
  exit 1
fi

# run from third-party directory only
cd ${0%/*} || exit 1
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}
. etc/tools/ThirdPartyFunctions
. etc/tools/makeExtraThirdPartyFunctions

#end of initializations -------------------------------------------

create_gcccompatible_library()
{
  echo -e "\033[1m creating libmpi.a \033[0m"
  cd $MPI_ARCH_PATH/lib
  gendef - $MPI_ARCH_PATH/bin/libmpi.dll > openmpi.def
  dlltool -d openmpi.def -l libmpi.a -D libmpi.dll
}

patch_mpi_includes()
{
  echo -e "\033[1m patching mpi.h \033[0m"
  if [ "$WM_ARCH_OPTION" = "64" ]; then
    cd $MPI_ARCH_PATH/include
    sed -i -e 's=defined(_WIN32)=defined(_WIN32) || defined(WIN64) || defined(_WIN64)=g' mpi.h
  fi
}


#script start ------------------------------------------------------

if [ ! -e "$MPI_ARCH_PATH/bin/libmpi.dll" ]; then
  ./get-em so openmpi-win=default || {
    echo "Unable to retrieve and unpack necessary files for Open-MPI."
    exit 1
  }
fi

if [ ! -e "$MPI_ARCH_PATH/lib/libmpi.a" ]; then

  echo -e "\033[1m Generating Open-MPI library interfaces for MinGW... \033[0m"

  create_gcccompatible_library
  patch_mpi_includes
  echo -e "\033[1m All done. \033[0m"
else
  echo -e "\033[1m Open-MPI library interfaces for MinGW are already built and ready to use. \033[0m"
fi
