#!/bin/sh
#------------------------------------------------------------------------------
# License
#     Copyright (C) 2011-2014 blueCAPE Lda
#
#     This file is derived from the branch "get-em" available here:
#         https://github.com/wyldckat/ThirdParty-2.0.x/commits/get-em
#
#     This file is part of blueCAPE's unofficial mingw patches for OpenFOAM.
#     For more information about these patches, visit:
#         http://bluecfd.com/Core
#
#     It's licensed under the same license of the target software, namely GPL
#     v3 or above (see <http://www.gnu.org/licenses/>).
#
#     The target software is OpenFOAM(R) <http://www.openfoam.org>. It's
#     trademarked by and Copyright (C) 2011-2014 OpenFOAM Foundation
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# File
#     etc/tools/get-em/gcc
#
# Description
#     This script will gather the necessary information about the application.
#     This script expects to be executed in the base folder where the get-em script is.
#
# FIXME
#   * Currently it is hard-coded to use tar.gz.
#
#------------------------------------------------------------------------------

versionVar="gcc_version"
appName="gcc"
appDefaultSep="-"
appFileExt="tar.gz"


#
# Shows the description for this application.
#
GE_showDesc()
{
  echo "gcc - Retrieve the whole gcc package (gcc, g++, ada, fortran, go, \
java, objc). Size: 60 to 100MB"
}


#
# Updates the file defined in $versionCacheFile, using the mirror url $1 and
# uses the $testFile as a sandbox.
#
GE_update()
{
  wget "$1" -O $testFile > /dev/null 2>&1
  grep -e "gcc-[0-9]\.[0-9]\.[0-9]" $testFile | \
    grep -v -e "gcc-[0-3]\.[0-9]\.[0-9]" | \
    grep -v -e "gcc-4\.[0-2]\.[0-9]" | \
    sed -e 's=.*>\(gcc-.*\)/<.*=\1=' -e 's_-_=_' | \
    sort -u > $versionCacheFile
  rm $testFile
}


#
# Receives the mirror url $1, the real version $2 and the variable $appFileExt.
# Shows the full url for the file to be downloaded.
#
GE_geturl()
{
  echo ${1}gcc-$2/gcc-$2.$appFileExt
}


#
# Echoes the relative path of the target folder. Receives the real version $1.
#
GE_getfolder()
{
  echo gcc-$1
}


#
# Echoes the number of folder levels counting from the left that the unpacker
# should drop. This is (or at least it should be) a prevention mechanism for
# tar/zipbombs.
#
GE_levels()
{
  echo 1
}


# Finally source the master script
. etc/tools/get-emScriptFunctions
